export const HOME_SCREEN="HOME_SCREEN"
export const DETAIL_PRODUCT_SCREEN="DETAIL_PRODUCT_SCREEN"
export const PRODUCT_LIST_SCREEN="PRODUCT_LIST_SCREEN"



// AUTH
export const LOGIN_SCREEN="LOGIN_SCREEN"

