export const HOME_SCREEN="HOME_SCREEN"
export const DETAIL_PRODUCT_SCREEN="DETAIL_PRODUCT_SCREEN"
export const PRODUCT_LIST_SCREEN="PRODUCT_LIST_SCREEN"
export const ACCOUNT_SCREEN="ACCOUNT_SCREEN"
export const BLOG_SCREEN="BLOG_SCREEN"
export const READ_BLOG_SCREEN="READ_BLOG_SCREEN"
export const BRAND_LIST_SCREEN="BRAND_LIST_SCREEN"
export const CATEGORY_LIST_SCREEN="CATEGORY_LIST_SCREEN"


export const AUTH_NAV="AUTH_NAV"
export const MAIN_NAV="MAIN_NAV"


// AUTH
export const LOGIN_SCREEN="LOGIN_SCREEN"
export const REGISTER_SCREEN="REGISTER_SCREEN"


